### ISSUE TITLE
About the pre-trained model and data augmentation

### ISSUE THREAD

**Issue by SicongLiang** [SimonVandenhende/Multi-Task-Learning-PyTorch#10]
Thank you for your sharing about multi-task learning problem which is very useful!

You have mentioned you used the pre-trained models, e.g., pre-trained Resnet-50, and data augmentation trick in Sec 4.1.4 Training Setup. Therefore, is it right that the results in NYUD-v2 dataset which are reported in TABLE 5(c) in your paper are also based pre-trained Resnet-50 model with data augmentation? Besides, dose using the pre-trained models and data augmentation improve the performance very much?

Thanks for your patience again!

**Comment by SimonVandenhende** [comment]
I always used a pre-trained ResNet-50 model with data augmentation.
However, I did not retrain the PAD-Net, JTLR and PAP-Net model. However, you should get similar numbers for the other models.
