### ISSUE TITLE
About the code of pix acc & mean acc for segmentation and the code of rel & \delta 1 & \delta 2 & \delta 3 for depth 

### ISSUE THREAD

**Issue by TianhaoFu** [SimonVandenhende/Multi-Task-Learning-PyTorch#11]
Hi, I noticed that this repository did't inculde the code of **pix acc & mean acc for segmentation** and the code of **rel & \delta 1 & \delta 2 & \delta 3 for depth task**. But in your papre you provide these metrics result . 

Could you provide these evaluation code ？

Thank you so much :) 👍

**Comment by SimonVandenhende** [comment]
Hi

Thanks for the interest. I did not include these in the public implementation.
However, it should not be that hard to add them to the evaluation code in ./evaluation/eval_semseg.py and ./evaluation/eval_depth.py. 
If you have any further questions, I would be happy to help.
