### ISSUE TITLE
Setup issue

### ISSUE THREAD

**Issue by danielp3011** [SimonVandenhende/Multi-Task-Learning-PyTorch#15]
I am getting a path error since a part of the path is doubled in the code when running:
```shell
python main.py --config_env configs/env.yml --config_exp configs/pascal/hrnet18/mti_net.yml
```
The path looks like this:
```python
../../../data2/yd/mti/datasets/PASCAL_MT/../../../data2/yd/mti/datasets/PASCAL_MT/human_parts/2008_000008.mat
```
For us it seems like there is an error in ```data/pascal_context.py```  here:
In line 111 the part_gt_dir is defined as an extension to self.root:
```python  
part_gt_dir = os.path.join(self.root, 'human_parts')
```
however in line 172 self root is joined with part_gt_dir, so with an extension of itself:
```python 
_human_part = os.path.join(self.root, part_gt_dir, line + ".mat")
```

**Comment by SimonVandenhende** [comment]
Hello. How did you specify your path in the utils/mypath.py file?
I only tested the code when using absolute filepaths. Perhaps the error occurs when using a relative filepath.
