### ISSUE TITLE
Question on Multi Task Evaluation Criteria

### ISSUE THREAD

**Issue by bpinaya** [SimonVandenhende/Multi-Task-Learning-PyTorch#4]
Your survey on MTL is awesome! Amazing work, I got a quick question, in section 4.2.1 Evaluation Criterion you mention:
```
where li = 1 if a lower value means better performance for metric Mi of task i, and 0 otherwise.
```
But in the function `calculate_multi_task_performance`
```python
    for task in tasks:
        mtl = eval_dict[task]
        stl = single_task_dict[task]
        
        if task == 'depth': # rmse lower is better
            mtl_performance -= (mtl['rmse'] - stl['rmse'])/stl['rmse']

        elif task in ['semseg', 'sal', 'human_parts']: # mIoU higher is better
            mtl_performance += (mtl['mIoU'] - stl['mIoU'])/stl['mIoU']

        elif task == 'normals': # mean error lower is better
            mtl_performance -= (mtl['mean'] - stl['mean'])/stl['mean']

        elif task == 'edge': # loss lower is better
            mtl_performance += (mtl['odsF'] - stl['odsF'])/stl['odsF']

        else:
            raise NotImplementedError
```
`task == 'edge': # loss lower is better` but it's adding instead of subtracting, why is that?

Also I've trying to retrain individual tasks like `depth` or `semseng` in a multi-gpu setup but it crashes and reboots!! (I'll probably look into this latter, but wondering if you ever encountered it)

Again, awesome work! Thanks for sharing

**Comment by SimonVandenhende** [comment]
Indeed, the sign should be reversed. At the time, I saved all models offline and evaluated them afterwards, printing the loss as evaluation criterion to monitor progress. This was merely to speed things up. I will fix this.

**Comment by SimonVandenhende** [comment]
As for the multi-gpu setup, I was able to run experiments which required a lot of memory on high-end gpu's (>32GB) so I did not experiment with the multi-gpu setup.

**Comment by bpinaya** [comment]
Thanks for the quick reply and clarification!
