### ISSUE TITLE
ResNet-50 single task baseline hyperparameters

### ISSUE THREAD

**Issue by zergzzlun** [SimonVandenhende/Multi-Task-Learning-PyTorch#5]
Hi there, thank you for open-sourcing your amazing work.

I trained ResNet-50 single-task baseline for segmentation task using config file ["configs/nyud/resnet50/semseg.yml"](https://github.com/SimonVandenhende/Multi-Task-Learning-PyTorch/blob/master/configs/nyud/resnet50/semseg.yml). However, I can get at best 40.4 mIoU on NYUD-v2 dataset, which is lower than 43.9 reported in the survey. Can you please provide the hyperparameter used in the survey or some hint to reach 43.9 mIoU?

Thanks in advance.

**Comment by SimonVandenhende** [comment]
Hi. Thanks for the interest. 
Please refer to issue #1 . 
The results on NYUD were obtained using different augmentations, compared to the ones I opensourced here. 
As promised in issue #1. I will work to integrate this into the code base this month, and try to opensource the pre-trained models.

**Comment by SimonVandenhende** [comment]
I am working to fix the issue this week.

**Comment by SimonVandenhende** [comment]
The issue should be fixed. Please refer to #1 for more information.

**Comment by zergzzlun** [comment]
> The issue should be fixed. Please refer to #1 for more information.

Many thanks.

**Comment by zergzzlun** [comment]
> The issue should be fixed. Please refer to #1 for more information.

It seems the correct version of NYUDv2 dataset cannot be downloaded right now. The URL is '/TO/BE/DEFINED/' in the new version of dataloader: [link](https://github.com/SimonVandenhende/Multi-Task-Learning-PyTorch/blob/master/data/nyud.py#L29).

**Comment by SimonVandenhende** [comment]
Should be fixed now. I forgot to commit the latest change to download the data automatically.
Sorry for the inconvenience.

**Comment by zergzzlun** [comment]
> Should be fixed now. I forgot to commit the latest change to download the data automatically.
> Sorry for the inconvenience.

Thanks for the update.
